# Generated by Django 4.0.4 on 2022-05-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badword', models.CharField(max_length=100)),
                ('severity', models.CharField(blank=True, choices=[('X', 'Explicit'), ('Q', 'Questionably Explicit')], default='X', max_length=2)),
            ],
        ),
    ]
